//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Entity_DAL.MedelsDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name_sity { get; set; }
        public Nullable<int> id_country { get; set; }
        public Nullable<int> id_region { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
