//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Entity_DAL.MedelsDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        public Magazine()
        {
            this.Products = new HashSet<Product>();
            this.UserMagazines = new HashSet<UserMagazine>();
        }
    
        public int id { get; set; }
        public string name_magazine { get; set; }
        public string C_image { get; set; }
        public int C_status { get; set; }
        public Nullable<int> id_category { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UserMagazine> UserMagazines { get; set; }
    }
}
