//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Entity_DAL.MedelsDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Baskets = new HashSet<Basket>();
            this.Comments = new HashSet<Comment>();
            this.LastViews = new HashSet<LastView>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string delivery_date { get; set; }
        public double price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> id_brand { get; set; }
        public string currency { get; set; }
        public string C_description { get; set; }
        public string producer { get; set; }
        public Nullable<int> id_category { get; set; }
        public string C_image { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> id_magazine { get; set; }
        public Nullable<int> C_status { get; set; }
        public Nullable<int> id_subcategory { get; set; }
    
        public virtual ICollection<Basket> Baskets { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<LastView> LastViews { get; set; }
        public virtual Magazine Magazine { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
